program enrichment
implicit none
integer::i,j,iframe,nframe,iligand,jligand,nligand,nligand_half
real:: dis_cut,t,enrich
real,allocatable::dist_P_L(:,:),bound_L(:),unbound_L(:),bound_L_as(:)
character(len=7) :: junk1


!***Input parameters***
!No of frames
nframe=198
!No of ligands
nligand=6
nligand_half=int(nligand/2)
!Cut-off protein-ligand distance for bound ligand
dis_cut=30

!***Input file (Protein-ligand diatnce)*** 
open(unit=1, file='dist_P-L.dat', action='read')

!***Output files***
!output for time evolution population of ligands 
open(unit=100, file='population.dat', action='write')
!output for enrichment
open(unit=101, file='enrichment.dat', action='write')
!output for %enruchment
open(unit=102, file='enrichment_percent.dat', action='write')

!***Allocating the arrays***
allocate(dist_P_L(nframe,nligand))
allocate(bound_L(nligand),unbound_L(nligand),bound_L_as(nligand))
!***Reading the input distance file generated by cpptraj***
!open(unit=1, file='dist_P-L.dat', action='read')
do i=1, nframe
 read(1,*) junk1, dist_P_L(i,:)
  enddo
!***Calculation of population and enrichment***
do iligand=1, nligand
  bound_L(iligand)=0.0
  unbound_L(iligand)=0.0
   enddo

do iframe=1, nframe
  enrich=0
   do iligand=1, nligand
    if (dist_P_L(iframe,iligand) < dis_cut ) then
      bound_L(iligand) = bound_L(iligand) + 1
    else
      unbound_L(iligand) = unbound_L(iligand) + 1
    endif
     enddo

do iligand=1, nligand
  bound_L_as(iligand)=bound_L(iligand)
   enddo
do iligand=1, nligand-1
      do jligand=iligand+1, nligand
        if (bound_L_as(iligand)>bound_L_as(jligand)) then
          t=bound_L_as(iligand)
          bound_L_as(iligand)=bound_L_as(jligand)
          bound_L_as(jligand)=t
        endif
         enddo
          enddo
do iligand=1, nligand_half
  if (bound_L(iligand) > bound_L_as(nligand_half) ) then
    enrich=enrich+1
  endif
   enddo
write (100,*) iframe, (bound_L(:)/iframe)*100
write (101,*) iframe, enrich
write (102,*) iframe, (enrich/nligand_half)*100
enddo
end program enrichment
